### ISSUE TITLE
Helper function to set up a test repository ready to use with fledge

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#102]
so that we can create meaningful examples.

Should use `withr::local_tempdir()` or perhaps `withr::with_tempdir()` .

Extract from vignette.

Optionally, connect to a local remote repository (i.e. a bare repo in `tempdir()`).

Originally part of #8.

**Comment by maelle** [comment]
let "open" be an argument in order to be able to use the test repo interactively.

**Comment by krlmlr** [comment]
Good idea!
