### ISSUE TITLE
Add formal tests

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#103]
wherever possible.

One problem/feature with snapshot testing of vignettes is that these tests don't count for the coverage.

**Comment by maelle** [comment]
Might happen with examples so maybe partly in 0.1.0? #113 adds a test.

**Comment by krlmlr** [comment]
This and many many other issues will be much easier with #331.

**Comment by maelle** [comment]
What else exactly would be tested?

**Comment by krlmlr** [comment]
We're good here, let's continue in the new wishlist issue.
