### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#104]
Document pre-requisites, explain tag vs release and use of each, clarify README statement about numbers being cheap, clarify squash commits vs other alternatives.

Also list resources about how to write changelogs (e.g. tidyverse style guide)

**Comment by maelle** [comment]
When it is ok to edit manually the changelog, why it's so important to have the tags (the messages used automatically are the ones written since the last tag).

**Comment by maelle** [comment]
in the main vignette at "When you want to assign a version number to the current state of your R package" maybe add some reference (I see what switching focus means, but maybe some link might be useful). Make the usefulness of the version number explicit (e.g. one would see it in bug reports from users; it might help users depending on how they install your package).

**Comment by krlmlr** [comment]
Should we give a few more examples?

- When merging a major change
- After merging a few pull requests
- At the end of a working day
- Once per week

?

I think the main point is that you want to make the changes explicit in your NEWS.md “regularly” or “when it makes sense”, whatever that means. The cadence varies even in my own projects, I guess there is no “one size fits all” rule here.

**Comment by krlmlr** [comment]
The best moment is between bump_version() and finalize_version(push = TRUE). You can edit at any time, but only between those two calls the text in the changelog will be captured in the tag message.

GitHub lists annotated tags, e.g. see https://github.com/r-dbi/RMariaDB/releases <https://github.com/r-dbi/RMariaDB/releases> — click on the ellipsis next to v1.1.1.900x .

**Comment by maelle** [comment]
I'm thinking about what should be done to make the use of the "merge.ff" clearer.
* A link to some explanation. Maybe https://www.atlassian.com/git/tutorials/using-branches/git-merge although it doesn't mention the option per se.
* Would it be risky to suggest setting the option globally.

**Comment by maelle** [comment]
Also, to go with explanation of tags, maybe a recommendation of what to tell the users to install in a README when a package uses fledge (the latest tagged version if they want a development version, as opposed to getting what's on the default branch?).

**Comment by maelle** [comment]
> Also, to go with explanation of tags, maybe a recommendation of what to tell the users to install in a README when a package uses fledge (the latest tagged version if they want a development version, as opposed to getting what's on the default branch?).

Does this make any sense @krlmlr? In hindsight I'm thinking maybe not.

**Comment by krlmlr** [comment]
The default branch should be the same as the most recent tag most of the time. I think this relates to the question when to bump -- in a nutshell maybe "whenever you're done for now" is the right answer here. I admit that I often forget to bump too.

We could point to the tags as a more coarse-grained history compared to top-level merges in the docs.
