### ISSUE TITLE
Add motivation

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#105]
Document downsides and alternatives (pre-commit CI?). Justify why the discipline of fledge usage is worth it.

- Maybe tell why the package was created.
- Any success stories from external users?

None of those are needed, but nice illustrations if available.

**Comment by maelle** [comment]
in short this part would answer "why should you bother" :-)

**Comment by krlmlr** [comment]
To some extent, Git conflicts in `NEWS.md`, and typing the same info twice (commit message and changelog).

You can avoid typing the commit message with pull requests, but this makes it harder to understand what a merge is about, and doesn't give you a changelog unless you ask contributors to edit `NEWS.md` which is prone to conflicts.

**Comment by maelle** [comment]
Thanks! I have content for this in my head too now after learning more about fledge.

**Comment by maelle** [comment]
Some draft

----

Do you want to provide a changelog ([NEWS.md](https://blog.r-hub.io/2020/05/08/pkg-news/#why-write-the-changelog-as-newsmd)) more informative than ["bug fixes and performance improvements"](https://twitter.com/EmilyKager/status/1413628436984188933) to the users of your package?
What you can do is

- Update NEWS.md right before release by reading through commit messages. Not fun!
- Update the changelog in every commit e.g. in every PR. Now, if there are several feature PRs around that update the changelog, you'll have a few clicks to make to tackle conflicts. Easy enough, but not fun.
- Use fledge!


All you need to do is

- Add a hyphen `-` or `*` at the beginning of important commit messages e.g. the squash commits that merge a Pull Request. These are the commit messages that'll be recorded in the changelog eventually! Exclude housekeeping parts of the message by typing them after a line `---`.

```text

- Add support for bla databases.

```

or 

```text

- Add suport for bla databases.

---

Also tweak the CI workflow accordingly. :sweat:

```

- Run `fledge::bump_version()` regularly e.g. before every coffee break or at the end of the day.

- Run `fledge::finalize_version()` if you add to edit NEWS.md manually (e.g. if you made a typo).

- Babla at release.

These habits are worth learning!

**Comment by krlmlr** [comment]
I love it!

**Comment by krlmlr** [comment]
Also: https://twitter.com/_ColinFay/status/1442822204840890375.

**Comment by maelle** [comment]
I like that tweet, however note that the attached images have no alternative text so if used it'd need some explanation of the images.
