### ISSUE TITLE
Release fledge 0.1.0

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#109]
First release:

* [x] `usethis::use_cran_comments()`
* [x] Proof read `Title:` and `Description:`
* [x] Check that all exported functions have `@returns` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] Remove CRAN badge from README.
* [x] `devtools::build_readme()`
* [x] [`urlchecker::url_check()`](https://github.com/r-lib/urlchecker)
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] Review pkgdown reference index for, e.g., missing topics
* [x] `fledge::bump_version("minor")`

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] Update install instructions in README
* [x] Finish blog post
* [x] Tweet
* [x] Add link to blog post in pkgdown news menu
* [x] Re-add CRAN badge in README.

**Comment by maelle** [comment]
>  Check licensing of included files

No included files, correct?

**Comment by maelle** [comment]
Winbuilder check started

**Comment by maelle** [comment]
Ironically what's missing from the check list is the fledge stuff :-)

**Comment by maelle** [comment]
:raised_eyebrow: https://win-builder.r-project.org/F6XxursP1Fli/

**Comment by krlmlr** [comment]
All files our own, yes.

**Comment by krlmlr** [comment]
What is the failing galley run on Windows about? Should we `skip_on_os()` ?

**Comment by maelle** [comment]
I've re-launched all checks with a new version number (temporary) as I wonder whether that's what makes check fail.

**Comment by maelle** [comment]
> What is the failing galley run on Windows about? Should we skip_on_os() ?

Let me look :female_detective:

**Comment by maelle** [comment]
I do not understand why the winbuilder checks (and R-hub checks) fail, I made the version 0.0.6 before sending them. https://win-builder.r-project.org/kEhVC26a7uhb/00check.log

**Comment by maelle** [comment]
Maybe I did the aspell stuff wrong

**Comment by maelle** [comment]
Via `devtools::check_win_devel()` I'm getting `Failed FTP upload: 550`

**Comment by maelle** [comment]
I think this can be closed?
