### ISSUE TITLE
Clarify error message for "forbidden_modifications"

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#111]
At the moment if you have DESCRIPTION with uncommitted changes and try to run `fledge::bump_version()`, the error message is not explicit.

I'd expect some clear instructions à la https://github.com/r-lib/usethis/blob/3385e148c06b13a34406a455d7a7ab0785993201/R/utils-git.R#L156

**Comment by krlmlr** [comment]
Good point, I postponed -- if you want to show the behavior in a vignette, we solve now (DDD, documentation-driven development).

**Comment by maelle** [comment]
I think it's fine. I stumbled upon another error message that could be improved: I had forgotten to add & commit `tests/testthat.R` (removing the "add ." and forgetting to add one of the files :sweat_smile: ) so `bump_version()` failed.

**Comment by maelle** [comment]
Ah no the error message was the same actually! I forgot to add DESCRIPTION after adding the tests.
