### ISSUE TITLE
Add how to close an issue with a PR without having the fix in the message

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#114]
For those who use GitHub, and PRs.

If one links the issue to the PR via the PR first comment, then the "squash and merge" comment will not have to contain "Fixes <issue-number>".
Or put that fixes message below three dashes.

**Comment by krlmlr** [comment]
I think it's good practice to have the link in the first comment anyway.

**Comment by maelle** [comment]
Exactly why it's good to remind of its existence :grin:
