### ISSUE TITLE
How can a collaborator contribute the NEWS item?

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#115]
A small caveat. Say someone makes a PR to add a feature. Without fledge, this person might edit NEWS.md and the maintainer can comment on that. With fledge, it's less natural for the contributor, who's not going to merge their own PRs, to contribute the NEWS item phrasing. (it's a small caveat, that contributor can get to that stage if granted write access later).

**Comment by krlmlr** [comment]
We can ask users to contribute a NEWS message in a comment or as part of the first message in a PR. Other than that I feel it's more efficient if the maintainer types the message themselves -- they will need to edit the change log anyway.

One motivation for fledge was to avoid Git conflicts in `NEWS.md` . The other workflow feels flawed anyway.

**Comment by maelle** [comment]
> I wonder if we should teach fledge to interact with the GitHub API to extract information from commits that point to a pull request (Merge pull request #xxx) but lack a bullet point.

Or teach users :grin:

**Comment by maelle** [comment]
this issue action = maybe a caveat to the docs.
