### ISSUE TITLE
Add a fledge.quiet option?

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#117]
It'd be nice when running the tests.

**Comment by krlmlr** [comment]
Silence these messages with `expect_snapshot()` ?

**Comment by maelle** [comment]
What do you mean exactly? There is no option in `expect_snapshot()` for silencing messages?

**Comment by krlmlr** [comment]
`expect_snapshot()` captures the messages and also has the side effect of recording them.

**Comment by maelle** [comment]
Oh that's a cool idea, now done in #113.

However I still think there'd be some value in having a fledge.quiet option. :thinking:

**Comment by maelle** [comment]
Argument from the recent snapshot test: with the option one could avoid the snapshot of messages that could be not as stable as wished.

**Comment by maelle** [comment]
For reference https://github.com/r-lib/usethis/blob/master/principles.md#communicating-with-the-user
