### ISSUE TITLE
Does cynkra have an R-universe?

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#119]
Wondering about this as I re-read the installation instructions.

**Comment by krlmlr** [comment]
We do, but for some reason fledge isn't listed there: https://github.com/r-universe/cynkra .

**Comment by maelle** [comment]
It's because fledge isn't on CRAN yet.

If you want it to be listed there

* create a repo github.com/cynkra/fledge
* fill the necessary JSON metadata in a file as documented in https://ropensci.org/blog/2021/06/22/setup-runiverse/#the-packagesjson-registry-file

**Comment by krlmlr** [comment]
I have invited you to the repo. Would you like to do the setup?

**Comment by maelle** [comment]
Yep!

**Comment by maelle** [comment]
Are there other packages that should be listed in packages.json? (apart from fledge, dm, indiedown). I see a few pinned repos.

**Comment by krlmlr** [comment]
Good catch -- cynkrathis, munch, and tv are good too.

**Comment by jeroen** [comment]
@krlmlr you can add them to https://github.com/cynkra/universe

Fledge is there now: https://cynkra.r-universe.dev/
