### ISSUE TITLE
Remove dependency on dev rlang

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#124]
This now blocks r-universe builds.

- [ ] Clear GHA cache by changing the cache key
- [ ] Work around in tests: if snapshot tests show differently with dev rlang, test only for dev rlang and skip for released rlang

Not a priority, but perhaps necessary if the rlang update doesn't make it to CRAN before we send fledge.

**Comment by maelle** [comment]
Or make the dev dependency useless right away via #117 :grin: (the dependency is due to the message snapshot)
