### ISSUE TITLE
Why recommend bump_version() and then finalize_version()?

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#127]
In the README and fledge.Rmd both functions are recommended to set things up. I am not sure I understand why as `bump_version()` already updates NEWS, the version number and actually calls `finalize_version()` if "dev"?

**Comment by maelle** [comment]
Links to potentially outdated recs

* https://github.com/cynkra/fledge#usage (the two first items)
* https://cynkra.github.io/fledge/articles/fledge.html#initial-configuration

**Comment by maelle** [comment]
related question https://github.com/cynkra/fledge/pull/128/files#r715652347

**Comment by krlmlr** [comment]
After `bump_version()` you still can edit `NEWS.md` and call `finalize_version()` again. I agree the docs can be improved.
