### ISSUE TITLE
pkgdown preview

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#135]
Following https://github.com/cynkra/fledge/pull/128#issuecomment-932496862

* From reading the GHA workflow, using this will overwrite the current dev website? Why not create a Netlify website for PR previews (for internal PRs)? That's what the pkgdown repo itself has.
* At the moment with the desc bug the pkgdown website won't render with the dev version of pkgdown.

**Comment by krlmlr** [comment]
I'd rather avoid maintaining a Netlify site for each project at this time. We can get a preview by naming a branch `docs*`, this works well enough in practice. (Yes, it overwrites the current dev documentation, need to keep in mind to have only one `docs` branch at any time.)

**Comment by krlmlr** [comment]
Thanks. Are multiple GH repos pushing to the same Netlify site?

**Comment by maelle** [comment]
Not in the examples I mentioned. I can't foresee any issue (but who knows :grimacing: ) as each commit gets its own URL.

**Comment by krlmlr** [comment]
Should be good now.
