### ISSUE TITLE
Add a render README PR command?

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#136]
To make it easier to use https://github.com/r-lib/downlit/tree/f-readme-document?rgh-link-date=2021-10-01T19%3A30%3A00Z

**Comment by maelle** [comment]
what's the status of that downlit branch? 
I think md_document recently gained downlit support?

**Comment by krlmlr** [comment]
Hm, it's not obvious from `?rmarkdown::md_document` .

**Comment by maelle** [comment]
I was confused, indeed it's not yet implemented https://github.com/rstudio/rmarkdown/issues/2284

**Comment by maelle** [comment]
Or should fledge switch to the official downlit?

**Comment by maelle** [comment]
Add it to Config/Needs/readme
