### ISSUE TITLE
Support conventionalcommits syntax

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#145]
Cf https://github.com/conventional-commits/conventionalcommits.org + https://github.com/cynkra/fledge/issues/20#issuecomment-929834045 by @rtaph

**Comment by maelle** [comment]
@krlmlr if we were to implement this, a challenge would be to know what syntax a package uses (default or conventional commits). How about storing the info in a DESCRIPTION field like testthat edition?

**Comment by maelle** [comment]
Not directly related to the feature, I wonder whether conventional commit users often use pre-commits to check their commit messages (not that it'd work for merging PRs anyway).

**Comment by maelle** [comment]
https://github.com/zeke/semantic-pull-requests

**Comment by maelle** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by krlmlr** [comment]
Installed the probot for fledge.

**Comment by krlmlr** [comment]
The GH docs mean that we don't need to interact with the API for squash commits, because the PR title can be copied automatically.

**Comment by maelle** [comment]
Yep.

And it also relates to the discussion around protected branches but I'll stop going into :rabbit: :hole: and concentrate on the syntax now. :grin:

**Comment by krlmlr** [comment]
@rtaph: Thanks, your input would be very valuable!

**Comment by maelle** [comment]
In the changelog

- should types become h2 
- should trailers (e.g. Reviewed-by) become something between parentheses.

**Comment by maelle** [comment]
And should the body be compacted into one single paragraph, or is it fine to have news item be several paragraphs :thinking:

**Comment by krlmlr** [comment]
Types become h2, but only during releases. For now let's keep it simple, and leave out the trailers. We would also ignore the body if it's not prefixed with a `<type>:` .

**Comment by maelle** [comment]
The body will never be prefixed by a type, only the description is.

I've just realized that at the moment when using a bullet you can have several items per commit message e.g.

```
- Adds bla
- Adds blop
```

which with conventional commit would not work.

**Comment by maelle** [comment]
Reg h2. For common types abbreviations it is easy enough to translate.

For custom ones later we might want to let users store a dictionary somewhere.

**Comment by krlmlr** [comment]
I'd suggest a simpler approach for now: treat header and body the same, just like fledge is doing today, only allow accepting type prefixes in addition to bullets.

**Comment by maelle** [comment]
to recognize the first trailer one needs info on the trailer line (`token: value`, `token # value`) and on the line before (which has to be a blank line). Now I'm wishing the git log were transformed to XML :grin:

**Comment by maelle** [comment]
(saw the answer before a bit late, sorry)

**Comment by maelle** [comment]
Needed for full support

- [  ] Docs of set up for successful conventional commit usage (pre-commit, or PR stuff + protected branch)
- [  ] Fledge to accept pre-commit messages as newsworthy
- [  ] Full parsing, grouping, sorting of the conventional commits
- [  ] Document that conventional commits are supported. Actually, put it front and center as it'd be an important feature.

The PR #188 only tackles the second point.

**Comment by krlmlr** [comment]
Only the second point seems good for a start. Please ping me for review.

**Comment by maelle** [comment]
Just parking some notes about parsing

- translating the types into actual words
- translating the different BREAKING CHANGES markers (the breaking change trailers, the "!").
- grouping the h2 together (i.e. all features together for instance)
- doing the same with the _scopes_ 
- ordering the h2 according to a given order (probably features first, and within h2, breaking changes first)

The two latter items would be useful for a function related https://github.com/cynkra/fledge/issues/147 to "merge" versions before a release.

**Comment by maelle** [comment]
I'm quickly looking at https://github.com/conventional-changelog/standard-version just because fledge should probably mimick what's done there.

**Comment by maelle** [comment]
https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md

**Comment by krlmlr** [comment]
How different is "conventional changelog" from our established `NEWS.md` format?

**Comment by maelle** [comment]
Not that different https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/CHANGELOG.md but the differences are important because of how pkgdown uses NEWS.md

What I think needs to be mimicked is the configuration (:innocent: ) of e.g. what abbreviations mean, of what types are hidden in the changelog.

**Comment by maelle** [comment]
One aspect of conventional commits that's hard to reconcile with e.g. https://style.tidyverse.org/news.html is that breaking changes are not a type, they qualify any type.

**Comment by maelle** [comment]
Where could users store abbreviations for their conventional commits usage. :thinking:

**Comment by krlmlr** [comment]
We could repeat breaking changes in their own header, and leave it to the user to reconcile.

Where do other conventional-commit users store their definitions?

**Comment by maelle** [comment]
Good idea to repeat the breaking changes!

> Where do other conventional-commit users store their definitions?

Apparently in https://github.com/conventional-changelog/standard-version#configuration=

`.versionrc.json` or `.versionrc` sound ok although the name might be confusing to fledge users?

**Comment by krlmlr** [comment]
We could do `fledge::edit_conventional_config()` ?

The [release-please project](https://github.com/googleapis/release-please) looks great, I wonder if we can offload some of the work we're doing there.

All of this seems out of scope for now.

**Comment by maelle** [comment]
Another particularly interesting aspect of that project is the use of footers for indicating several changes in a commit https://github.com/googleapis/release-please#what-if-my-pr-contains-multiple-fixes-or-features=

**Comment by krlmlr** [comment]
Let's wrap up here for now and list all remaining work in new separate issues, perhaps with a specific tag? CC support is very much experimental for now. Perhaps some things will be easier with #331, and we might want to rethink the whole approach.

**Comment by maelle** [comment]
https://github.com/cynkra/fledge/issues?q=is%3Aopen+label%3A%22conventional+commits+%3Asparkles%3A%22+sort%3Aupdated-desc :heavy_check_mark: (@rtaph please feel free to comment in any of yours, thanks again for the feature request :pray: )
