### ISSUE TITLE
NEWS.md file not changed

### ISSUE THREAD

**Issue by RobinHankin** [cynkra/fledge#150]
Another error that left me stumped.  I made a change, committed it with a starred message,  ran `bump_version()` but got a "subscript out of bounds" warning which I am unable to interpret, and the `NEWS.md` file remained empty (even though the log shows 3 NEWS-worthy entries, and the log also says the new entries have been added to `NEWS.md`).  Is the NEWs.md file being edited and then removed?

```
rhankin@limpet:~/rstudio/clock$ git show
commit a616c25c05b1df97e0814413a10970d32a219a23 (HEAD -> master)
Author: Robin Hankin <hankin.robin@gmail.com>
Date:   Thu Oct 28 21:52:00 2021 +1300

    * very important change

diff --git a/man/cclock.Rd b/man/cclock.Rd
index 9e7fc67..379df10 100644
--- a/man/cclock.Rd
+++ b/man/cclock.Rd
@@ -8,7 +8,7 @@
 cclock(x, ...)
 }
 \arguments{
-  \item{x}{Object of class \code{clock}; an integer vector}
+  \item{x}{Object of  class \code{clock}; an integer vector}
   \item{\dots}{Other arguments coerced to clock objects}
 }
 \details{
rhankin@limpet:~/rstudio/clock$ R -q -e "fledge::bump_version()"
> fledge::bump_version()
✔ Setting active project to '/home/rhankin/rstudio/clock'
→ Scraping 3 commit messages.
✔ Found 2 NEWS-worthy entries.

── Updating NEWS ──

→ Adding new entries to NEWS.md.

── Update Version ──

✔ Package version bumped to 0.0.4.9005.
→ Adding header to NEWS.md.
→ Committing changes.

── Tagging Version ──

→ Creating tag v0.0.4.9005 with tag message derived from NEWS.md.
• Edit 'NEWS.md'
! Call `fledge::finalize_version(push = TRUE)`.
NULL
Warning messages:
1: When processing NEWS.md: subscript out of bounds 
2: When processing NEWS.md: subscript out of bounds 
> 
> 
rhankin@limpet:~/rstudio/clock$ cat NEWS.md 
rhankin@limpet:~/rstudio/clock$ 
```

**Comment by maelle** [comment]
In this case, had you created the NEWS.md file first? (sorry, trying to make sense of what happened)

For info there's a demo in https://cynkra.github.io/fledge/dev/articles/demo.html

**Comment by maelle** [comment]
I think the problem is that https://github.com/RobinHankin/clock/blob/master/NEWS.md is an empty file, not an empty Markdown file. I was able to reproduce an error but if I add one empty line, things work.

@krlmlr should fledge be able to work with a completely empty NEWS.md file? Or at least error informatively?

**Comment by maelle** [comment]
For the record https://github.com/cynkra/fledge/discussions/149

**Comment by krlmlr** [comment]
Thanks, missed that.

We should support an empty and a missing `NEWS.md` file on input.
