### ISSUE TITLE
Why is news_path a variable?

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#151]
I.e.  why

```r
news_path <- "NEWS.md"
```

rather than 

```r
news_path <- function() {
  "NEWS.md"
}
```
? 

Wouldn't the latter be less surprising?

**Comment by maelle** [comment]
Same question reg `news_comment`

**Comment by krlmlr** [comment]
It's not even used consistently. We can make this a function.

Let's collect issues related to technical debt under a specific label and resolve later.
