### ISSUE TITLE
Fix vignette

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#176]

**Comment by maelle** [comment]
The problem is https://github.com/cynkra/fledge/blob/11b917c9f22f5d5d0f872078cf02d7be2c0f8aa4/vignettes/demo.Rmd#L368

@krlmlr I'm not entirely sure, as in tests, what the recommended workflow should be. `bump_version()` created a tag. Should there be at least a new commit before calling `finalize_version(push = TRUE)`? Should it not be called?

**Comment by krlmlr** [comment]
Thanks. After `bump_version()`, the user can call `finalize_version(push = TRUE)` directly, or edit `NEWS.md` and then call `finalize_version(push = TRUE)` . In RStudio, `bump_version()` opens `NEWS.md` for editing.

**Comment by maelle** [comment]
well it seems that with the changes made to `tag_version()` the user can't do that. :-(

**Comment by maelle** [comment]
The error is

```r
fledge::finalize_version(push = TRUE)
## → Resetting to previous commit.
## → Committing changes.
## 
## ── Tagging Version ──
## 
## ℹ Tag v0.0.0.9002 exists and points to the current commit.
## → Force-pushing tag .
## Error in libgit2::git_remote_push: invalid refspec refs/tags/
```

but earlier in the vignette the function is called without any issue.

**Comment by krlmlr** [comment]
The space between `tag` and `.` indicates that the tag name is empty`

**Comment by maelle** [comment]
oh good call, let me look into this
