### ISSUE TITLE
Fix aspell stuff

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#179]
It seems I wrongly created the .rds as it makes the remote checks (winbuilder, R-hub) fail :grimacing:

**Comment by maelle** [comment]
`saveRDS(c("versioning", "Versioning", "changelog", "NEWS.md"), file = ".aspell/fledge.rds", version = 2)`

**Comment by krlmlr** [comment]
Should we run this as part of `devtools::document()` , somehow ?

**Comment by maelle** [comment]
At least it'd be interesting to have a reminder somewhere indeed. Does the PR look good?

**Comment by krlmlr** [comment]
I'd rather review the PRs when we're in happy-green-build-land again.
