### ISSUE TITLE
What is force in push_tag

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#181]
https://github.com/cynkra/fledge/blob/e75bc1b46031ee908d8b061bbe79274778baabd0/R/finalize-version.R#L27-L31

@krlmlr what is `force` supposed to be?

**Comment by krlmlr** [comment]
Should this be an argument to `push_tag()` ?

**Comment by maelle** [comment]
yeah I imagine so?

**Comment by maelle** [comment]
the force that's around when the function is called is

```
force <- commit_version()
```

it is used for choosing whether to force the tag creation. Should it be passed to `push_tag()` or should `push_tag()` not have the argument at all?

**Comment by krlmlr** [comment]
Good catch. I implemented according to the inline textual comments, hope it doesn't break the tests.

**Comment by maelle** [comment]
@krlmlr narrator's voice "the tests were broken" :joy: the argument was missing in `push_tag()` although it was used inside the function, now fixed https://github.com/cynkra/fledge/commit/dbb15d336ffa0e7b5b551ad3572ff4fbf414f364
