### ISSUE TITLE
How to best merge main into the open PRs

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#183]
I actually rebased all my PRs but I assume that's not what is usually done here as I see commits with "merge" in the message. Happy to do things differently in the future.

I also see there's a merge PR command.

**Comment by krlmlr** [comment]
The merge PR command doesn't do much. I'm using "Refined GitHub", it offers an "update the base branch" link.

Rebasing is fine, but not necessary. I prefer merge over squash, because it's easier to find the branches that have been already merged, and it helps with `git bisect` occasionally.

**Comment by maelle** [comment]
I use the same extension, I need to look into this!
