### ISSUE TITLE
Add examples to all functions

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#21]
Requires #8.

**Comment by maelle** [comment]
Do you want this because of CRAN rules? Right now after working through the demo I'm thinking I'd see more value out of a diagram / decision tree to see when to use the functions.

**Comment by krlmlr** [comment]
CRAN rules, yes.

**Comment by maelle** [comment]
Isn't CRAN rule to have examples for at least some functions? Not necessarily all of them?

**Comment by krlmlr** [comment]
I'd like to err on the side of caution here, and minimize the interactions with CRAN as much as possible.

**Comment by krlmlr** [comment]
The examples should be runnable; for learning the vignette is much better, and a link should be there, we still need the examples to avoid questions from CRAN.
