### ISSUE TITLE
Add ability to prepand message on git commit message (for CI usage)

### ISSUE THREAD

**Issue by DarthHater** [cynkra/fledge#24]
Hi there,

Firstly, this library is neat! I'm attempting to use it on: https://github.com/sonatype-nexus-community/oysteR

Secondly, in order to properly use this in say CircleCI, or other CI systems, without causing an endless loop after we push a commit in, we would need something to allow us to prepend or append something on the git message, so it looks like so:

`[skip ci] Bump version to 0.0.2`

https://circleci.com/docs/2.0/skip-build/

This will prevent an endless loop of sorts in CI.

Cheers!

**Comment by krlmlr** [comment]
Thanks, auto-bump sounds like an interesting use case. Happy to review a PR that adds an optional argument to `bump_version()`, defaulting to the current state.

I prefer a more manual workflow, it's useful to have the tags and corresponding commits checked by default.

**Comment by DarthHater** [comment]
I've got a fork of the project now, a few technical questions:

`bump_version` and `bump_version_impl` would both need the additional optional param

Another way to potentially do this is to just look for `CIRCLECI` env variable inside of `get_commit_message` and if that is true, append? Part of me doesn't like that approach, while part of me does.

**Comment by DarthHater** [comment]
@krlmlr submitted an initial PR in #25, not tied to the implementation I did, if you got any feedback!

**Comment by krlmlr** [comment]
The implementation of `bump_version_impl()` has calls to `update_news()` and `update_version()`, both of which are public. For a CI workflow, all that is missing is

```r
git2r::add(".", c("DESCRIPTION", "NEWS.md"))
git2r::commit(".", get_ci_commit_message())
```

Bumping versions interactively and on a CI system seem to be two slightly different use cases -- in a CI workflow we don't need an "undo". Perhaps a new top-level function is the way to go?

Before sending a PR, can you experiment in a local `.Rprofile`?

**Comment by krlmlr** [comment]
This looks rather specialized. Please work around by using `git commit --amend` in CI.
