### ISSUE TITLE
Option to have only one blank line between headers

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#26]
I am using an auto-formatter for markdown files which auto-deletes all unnecessary blank lines (i.e. if there are two, it cuts these down to one).

This causes me to run `finalize_version()` / `commit_version()` after updating the NEWS file every time.

Would be great to have an option to customize this globally.

**Comment by krlmlr** [comment]
How about running the auto-formatter as a pre-commit hook or in some other automated way?
