### ISSUE TITLE
Add a switch to submit_cran() in release()

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#261]
Like an environment variable `JUST_EXPERIMENTING` or so. :sweat_smile:

**Comment by maelle** [comment]
Noting that for GitHub PR/issue API data, we have mock files for tests.

**Comment by maelle** [comment]
I think I'm seeing some incompatibility between `httptest::with_mock_dir()` and `with_repo()` :thinking:

**Comment by maelle** [comment]
https://github.com/nealrichardson/httptest/issues/74

**Comment by krlmlr** [comment]
This is about a specific implementation detail, we still want to think about testing. OTOH, the automated release process is "tested" every time somebody uses it.

Let's revisit this when we make a bigger attempt at testing "everything".
