### ISSUE TITLE
Allow for further development on the main branch between pre_release() and CRAN acceptance

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#264]
Maybe by splitting `pre_release()`.

**Comment by krlmlr** [comment]
We discussed protecting the main branch after `pre_release()`, but I no longer think this is necessary. Instead, I now believe it's sufficient to slightly alter the behavior of `bump_version("dev")` if a release branch exists.

- We no longer call `bump_version("dev")` in `pre_release()` .
- Accepting a release would consist of merging the release branch into the main branch, and then `bump_version("dev")` .
- We need to take special care to ensure that the release branch can be merged back into the main branch without conflicts even after `bump_version("dev")` on the main branch. This now is ensured by bumping before branching off, but I think it can be made work also if we defer the bumping.

**Comment by maelle** [comment]
Is this actually a duplicate of #59 :thinking:

**Comment by krlmlr** [comment]
Doesn't look like it is, #59 can happen anyway.

Taking this on now.

**Comment by krlmlr** [comment]
Now in #614.
