### ISSUE TITLE
Automate CRAN release

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#27]
Function name: `unleash()`.

We're implementing a state machine with three states.

Pre-condition: Version in `DESCRIPTION` via `desc::desc_get_version()` is identical to version in `NEWS.md`.

## State management

- [x] `DESCRIPTION`
- [x] `NEWS.md`
- [x] `cran-comments.md`
- [x] `CRAN-RELEASE`
- [ ] ~~`.fledge` (?)~~

## Pre-submission

Condition for state:

- [x] `length(unclass(package_version(x))) >= 4`: current version has >= 4 components.

Condition for action: none

Actions:

- [x] Create CRAN comments from template, see pillar for example
    - [x] `getRversion()`
    - [x] `rversions::r_release()`
    - [ ] Check recent changes to https://github.com/eddelbuettel/crp/commits/master
- [ ] ~~Check CI status~~
- [x] `devtools::check_win_devel()`
    - [ ] ~~parse e-mail (?)~~
- [x] `rhub::check_for_cran()`
- [x] `foghorn::cran_details()`

## Submission

Conditions for state:

- [x] `length(unclass(package_version(x))) <= 3`: current version has <= 3 components
- [x] `desc::desc_get_version()` is different from `available.packages()[pkg, "Version"]`

Conditions for action:

- [x] `fledge:::is_news_consistent()`
- [x] Check if CRAN comments is good, i.e., contain no `- [ ]`

Actions:

- [x] `devtools::submit_cran()`
- [ ] ~~Grab URL from e-mail~~
- [x] `fledge:::confirm_submission()`

## After acceptance

Condition for state:

- [x] `desc::desc_get_version()` is identical to `available.packages()[pkg, "Version"]`

Condition for action:

- [x] Check if GitHub PAT has necessary scope
- [x] Check if SHA same as recorded in `CRAN-RELEASE`

Actions:

- [x] `fledge::tag_version()`
- [x] `git push --tags`
- [x] `usethis::use_github_release()` (also removes `CRAN-RELEASE`)
- [x] `fledge::bump_version()`

## Everything else

Undefined.

**Comment by krlmlr** [comment]
@pat-s: I now think that all releases should be done in a release branch. So, `pre_release()` (?) would bump the version to patch/minor/major, create and push the branch, bump to dev, push master, switch to the branch, and do the remaining work there. Not sure how to support a workflow where NEWS isn't managed by us here.

**Comment by maelle** [comment]
Despite this, still ok to document the current recommended release workflow in the demo vignette?

I thought about this when drafting the list of things one needs to learn to do for using fledge (commit messages formatting, what fledge functions to run regularly `bump_version()` and if needed `finalize_version()`, what to do for release).

**Comment by pat-s** [comment]
I think documentation might be a bit outdated atm - also there is another approach in branch `f-27-automate` which does a lot more automation as the default branch.
This is not yet documented and I think we (@krlmlr) should meet and discuss at some point if this should get merged or how we want to proceed?

@maelle Are you actively helping here? :)

**Comment by maelle** [comment]
@pat-s, no, I'm just wondering how to best document how things work for now without making changes difficult. :-) (but after all if the change is "replace bunch of functions and steps" with "less steps, less functions" it can only go well even for the docs :-) )

**Comment by krlmlr** [comment]
fledge needs to go to CRAN before we start thinking about merging this.

**Comment by krlmlr** [comment]
Even if this means we need to spend time integrating documentation later.

**Comment by maelle** [comment]
But is there a status quo on what the currently recommended CRAN release workflow is? If so could you sum it up in a few lines? Then I can add "And fledge's team is working on making this even smoother".

**Comment by pat-s** [comment]
@maelle

- `pre_release()` 
	- Creates a new branch named `cran-<version>` and tag
	- Runs several pre-release checks
	- Updates NEWS
	- CRAN policy changes check (see e.g. https://github.com/mlr-org/mlr3filters/pull/115/files)
- `release()`
	- Upload to CRAN

- `post_release()`
	- Merge release branch into default branch
	- Update to dev version


In between, one can continue to work on the main branch if desired and eventually merge changes back into the release branch (or commit directly to it).

The overall idea is/was to have a "CRAN workflow" and a "simple dev workflow" (i.e. `bump_version()` in the main branch only). All of this needs to be written down properly in a vignette. If you would like to help and test it, I can eventually give you a kickstart in a call?

At some point, I was also working on a scheduled job which queries CRANs mails and is able to categorize them into "Acceptance mail", "Revision needed" etc. 
Based on these categories, the stages from above could be triggered automatically (e.g. if all pre-release checks are ok, `release()` is called, the pkg is automatically uploaded and the detection of the acceptance is recognized and the PR automatically merged).

But this is somewhat advanced and needs some time which is currently within other projects. Also it would require forwarding mails to a gmail account as it uses `gmailr` under the hood which many would not like I guess..
