### ISSUE TITLE
Add noop argument (or similar) to bump_version()

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#307]
```r
bump_version <- function(which = "dev", noop = c("bump", "noop", "fail")) {
  ...
}
```

**Comment by maelle** [comment]
underscore

or other name

**Comment by maelle** [comment]
I was thinking `force` would be a good name (TRUE = current behavior, FALSE = fail) but it is missing the noop behaviour. :sweat_smile: 

noop behavior for CI would be `try(bump_version(force = FALSE), silent = TRUE)`, so probably not a good argument name after all.

**Comment by maelle** [comment]
not force, something else with 3 options
