### ISSUE TITLE
Get the NEWS item from the PR title

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#308]
if not specified in the merge/squash commit message.

**Comment by krlmlr** [comment]
Do we even need that? It seems that titles in conventionalcommit style are automatically used when the "Merge" button is pressed?

**Comment by krlmlr** [comment]
See e.g. fc85b60 which is the result of merging #317. I didn't edit the merge commit message.

**Comment by krlmlr** [comment]
Weird, I can't reproduce it. Seems like we still need this.

**Comment by maelle** [comment]
> Weird, I can't reproduce it. Seems like we still need this.

What do you mean? GitHub should use the PR title for "squash and merge".

**Comment by krlmlr** [comment]
Yes, but not for "merge", which is also an important use case.

**Comment by maelle** [comment]
Some notes
- have a function `is_per_merge_message()`. "Merge pull request <url>".
- make sure the url is a GitHub repo url 
- check there is a GitHub PAT
- safely call the API.

**Comment by maelle** [comment]
Another note, as fledge will accept newsworthy items from bullet points, normal PR titles, conventional commits messages/PR titles, some items will be added with a h2, others not. So the items (bullet points, normal PR titles) added without h2 will look as if they belong to the last h2 header if there's one.

Ultimately it might be better to add the non conventional commits differently to make sure they end up right below the version h1 as opposed to after a conventional commit h2 they are unrelated  to.

**Comment by krlmlr** [comment]
Should we use

```md
## Uncategorized
```

when a mix of cc or non-cc messages is detected?
