### ISSUE TITLE
What if someone uses --- several times in a commit message

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#313]
should there be some sort of warning

**Comment by krlmlr** [comment]
Three dashes indicate end of useful contents. Is it similar to "what if somebody uses multiple `#` in a comment"?

**Comment by maelle** [comment]
I am no longer sure there should be a warning in this case. The current behavior is fine.

``` r
message <- "lalalala\n\n---\n\nblablabla\n\n---\n\nblop"
cat(message)
#> lalalala
#> 
#> ---
#> 
#> blablabla
#> 
#> ---
#> 
#> blop
fledge:::remove_housekeeping(message)
#> [1] "lalalala\n"
```

<sup>Created on 2022-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
