### ISSUE TITLE
where does range come from

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#316]
https://github.com/cynkra/fledge/blob/520b9b2e36da7bc58136378407f1f4454bfbeadf/R/update-news.R#L25

**Comment by maelle** [comment]
It does not error because it's a base function

**Comment by maelle** [comment]
it seems it was always undefined? https://github.com/cynkra/fledge/commit/dcf228604d296f66a75716418a16d457df2beddf

**Comment by maelle** [comment]
will fix with #307 (which is how I found this)

**Comment by krlmlr** [comment]
Good catch!
