### ISSUE TITLE
Document assumptions

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#32]
- Default branch is master (???)
- GitHub
- RStudio
- ...?

**Comment by maelle** [comment]
Very important to document that you need to have a remote that indicates the default branch _or_ to be using the same default branch name as your global/project `init.defaultbranch`.

**Comment by maelle** [comment]
Document this near Installation in the README, potentially as a Rmd fragment so it can be re-used elsewhere. "Installation and pre-requisites".
