### ISSUE TITLE
should cran be an argument of pre_release()

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#320]
`pre_release(cran = FALSE)` could then be used if your package is not on CRAN.
It wouldn't create `cran-comments.md`.
Maybe it should still encourage some sort of checks à la R-hub, maybe not.

**Comment by krlmlr** [comment]
I'll work on splitting `pre_release()` in sensible lower-level testable APIs so that users can also build their own strategies.

**Comment by maelle** [comment]
based on #658, no, it's tailored for CRAN.
