### ISSUE TITLE
Helper functions for ranges of commits

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#327]
- From a range of commits, extract newsworthy items.
- From a range of commits, count if there's any change -- removing commits from `bump_version()`.
- From a range of commits, count if there's any newsworthy change.

Is this what you meant in https://github.com/cynkra/fledge/pull/323#discussion_r873526108 @krlmlr?

**Comment by krlmlr** [comment]
The comment was about extracting the logic to determine if there are newsworthy commits. I guess we don't need to worry that much, we have tests now.
