### ISSUE TITLE
parse_conventional_commit() improvements

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#335]
https://github.com/cynkra/fledge/pull/332#pullrequestreview-979373248

**Comment by maelle** [comment]
In https://github.com/cynkra/fledge/pull/334/files#r877596135 @krlmlr asked

> We need to think about when to expand conventional-commit messages. I wouldn't mind if this happened only during pre_release(), are there constraints that would prohibit this?

Good question. I think that even before release there might be value in seeing the items grouped by type. Furthermore, that's the behavior there'd be for #147

**Comment by krlmlr** [comment]
We can improve the code the next time we touch it. Do we need to keep open issues about everything we encounter? I'm feeling slightly overwhelmed.
