### ISSUE TITLE
Sort NEWS.md entries according to conventional commits headers

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#336]

**Comment by maelle** [comment]
In https://github.com/cynkra/fledge/pull/334/files#r877596135

> Loose thought: if a mix of cc and non-cc messages is detected, we can list the non-cc messages under their own header "uncategorized"?

**Comment by maelle** [comment]
@krlmlr at the moment the biggest missing piece in conventional commits support is related to #147: imagine one runs `bump_version()` often as one should. One ends up with many version headers. Before a CRAN/big release it'd be nice to be able to merge the different versions into one single list of changes, re-organizing the items according to conventional commit headers.

From

```markdown
## fledge 1.1.2

### Documentation

- thing

### New features

- cool thing

## fledge 1.1.1

### Bug fixes

- Ouch

### New features

- Nice thing

```

to

```markdown
## fledge 1.2.0

### Documentation

- thing

### New features

- cool thing

- Nice thing

### Bug fixes

- Ouch

```

**Comment by krlmlr** [comment]
Perhaps we can wait with categorizing the entries until `pre_release()` ? In "changelog" format we would store raw entries, and put them under headers only when preparing a release?

With a good fledgeling we can also do this from a pre-categorized `NEWS.md` .

Either way, we're close.
