### ISSUE TITLE
Run devtools::document() as part of bump_version

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#34]
because it's forgotten too often.

**Comment by krlmlr** [comment]
And also render `README.Rmd`.

**Comment by krlmlr** [comment]
Needs {tasq}.

**Comment by maelle** [comment]
Or _error_ if these things aren't done, as a git hook would do?

**Comment by maelle** [comment]
I wonder if this really fits with the mission of fledge :thinking:

**Comment by krlmlr** [comment]
`document()` is now done in our workflows, rendering README remains manual because it's unstable all too often.

I wonder if the GHA workflow could render README *twice*, and commit only if it has changed (and issue a warning or something otherwise).

Anyway, not much more to do here.
