### ISSUE TITLE
Less vertical space in NEWS.md?

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#347]
Regarding empty lines between bullets, @krlmlr [wrote](https://github.com/cynkra/fledge/pull/343#discussion_r879368909)

> I find NEWS more concise if there is no empty line inbetween. Are there semantic differences?

My answer

- Depending on the Markdown parser the items might be items of a list or several lists, I suppose.
- I am used to empty lines in https://github.com/r-lib/pkgdown/blob/main/NEWS.md?plain=1
- However no mention of this in https://style.tidyverse.org/news.html

Should this be a configurable option? :innocent:

**Comment by krlmlr** [comment]
I have already adapted to the space. We'll bring this back when thinking about normalization.
