### ISSUE TITLE
Consolidate use of rematch2

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#352]

**Comment by maelle** [comment]
"why use rematch2" would be a nice short blog post idea

**Comment by maelle** [comment]
I see rematch2 actually has few reverse dependencies (which might make a blog post all the more useful, if you think more people should use it :grin:)

**Comment by maelle** [comment]
con of rematch2 in general: rematch2 uses tibble

**Comment by maelle** [comment]
pro: named groups :star_struck:

**Comment by krlmlr** [comment]
Not a priority, let's think about promoting rematch2 and rex.

**Comment by maelle** [comment]
btw I recently saw https://github.com/r-lib/usethis/blob/901dae0542f33697ec89268d52597ecc9e407a9c/R/utils-rematch2.R#L1
