### ISSUE TITLE
Feedback on `release()`

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#36]
```r
fledge::release()
Error: invalid version specification ‘3verse 0.1.2’, ‘3verse 0.1.1.9000’
Backtrace:
1: stop(gettextf("invalid version specification %s", paste(sQuote(unique(x[!ok])), 
2: .make_numeric_version(x, strict, .standard_regexps()$valid_package_version, 
3: package_version(headers, strict = TRUE)
4: is_news_consistent()
5: stopifnot(is_news_consistent())
6: release_impl()
7: force(code)
8: withr::with_dir(usethis::proj_get(), code)
9: with_repo(release_impl())
10: fledge::release()
```

NEWS.md looks good to me

```
# mlr3verse 0.1.2

- Add mlr3data (#3)


# mlr3verse 0.1.1.9000

- Internal changes only.
```

Somehow "mlr" is stripped from the specification?

**Comment by krlmlr** [comment]
A bad regex somewhere. Could you please take a look?

**Comment by pat-s** [comment]
I'd replace https://github.com/krlmlr/fledge/blob/c3cd4a172b6e69c2d3389ee9aa63ce1b2139d44e/R/auto.R#L117-L117

with `gsub("^# .* ", "", news[top_level_headers])`

---

`is_news_consistent()` gets the last two level 1 headers and checks if both are <= length(3).

https://github.com/krlmlr/fledge/blob/c3cd4a172b6e69c2d3389ee9aa63ce1b2139d44e/R/auto.R#L104-L118

Hence, the followings news entry is invalid

```
# packageName 0.1.2

- news


# packageName 0.1.1.9000
```

- Why only the last two headers? 
- If we assume that the CRAN version has length three, the dev version right before almost always has length 4.

**Comment by pat-s** [comment]
@krlmlr I'd like to release mlr3verse soon again and I am happy to try `fledge::release()` again. To do so, the `is_news_consistent()` needs to be resolved however.

If there is no capacity right now, I can try `release()` again for the next CRAN package.

**Comment by krlmlr** [comment]
During the release process the dev is supposed to reconcile the change log to release notes: remove redundancies, copy-edit, order by topic perhaps. No references to *.9000 versions should remain in NEWS. I'd argue it's sufficient to check the first two headers -- the current version and the one before that.

**Comment by pat-s** [comment]
I see. This action item could be added either as an item to the output of `pre_release()` or into `cran-comments.md` as a checkbox.

I'll clean up and proceed then.

**Comment by krlmlr** [comment]
I like a message for `pre_release()` -- there's already a ton of them, could definitely do better!

**Comment by pat-s** [comment]
> https://github.com/krlmlr/fledge/issues/36#issuecomment-644847747

FYI: This was commited btw.

**Comment by krlmlr** [comment]
I think we're good here. If not, please open a new issue.
