### ISSUE TITLE
Include reference to issue closed with a PR?

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#361]
https://github.com/cynkra/dm/commit/d1ab1fcb5bca29b145375b3c98c20355ab09e248

**Comment by maelle** [comment]
Currently looking for a programmatic way to find issues linked to a PR as I'd prefer to not re-invent the code GitHub has for finding linked issues (special words etc).

**Comment by maelle** [comment]
yay!

```
{
  repository(owner: "cynkra", name: "dm") {
    pullRequest(number: 1161) {
      id
      closingIssuesReferences(first: 50) {
        edges {
          node {
            id
            body
            number
            title
          }
        }
      }
    }
  }
}
```

https://stackoverflow.com/a/72967359/5489251

**Comment by maelle** [comment]
fledge needs to check the scope of the token
