### ISSUE TITLE
`pre_release()`: Add action item to clean up NEWS.md from .9xxx entries

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#37]
Otherwise `release()` fails.
See

_Originally posted by @pat-s in https://github.com/krlmlr/fledge/issues/36#issuecomment-649642168_

**Comment by maelle** [comment]
Or https://github.com/cynkra/fledge/issues/97 automatically?

**Comment by maelle** [comment]
@krlmlr I think this will be closed by #686?
