### ISSUE TITLE
Simple fledgling object

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#402]
Part of #331.

This object would only parse top-level headers (version, date, and perhaps format of the header), and contain the contents of the Markdown chunks between top-level headers as character vectors. Also, the relevant parts of `DESCRIPTION` (current version and date).

No tinkr. Parsing with regular expressions (e.g. `"^ *# +..."`) .

As simple as possible, to get us started.

**Comment by maelle** [comment]
There's already `get_news_headers()` to build upon (and `date_in_news_headers()`)

**Comment by maelle** [comment]
Use R6 like the other related packages? :innocent: (I like the idea of a desc-like object)

**Comment by maelle** [comment]
(or contribute to newsmd to make the NEWS object more hierarchical?)

**Comment by krlmlr** [comment]
I'd prefer immutable objects.
