### ISSUE TITLE
How to deal with `cran-comments.md` listed in `.gitignore`

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#41]
It just happened to me that a repo had `cran-comments.md`in `.gitignore`. Should we attempt to force add here?

Otherwise `pre_release()` fails.

**Comment by krlmlr** [comment]
Good point. We need to list this in the prerequisites, maybe we can check and alert the user? I wouldn't force-add.

https://git-scm.com/docs/git-check-ignore

**Comment by krlmlr** [comment]
Closed now.

**Comment by krlmlr** [comment]
Merged.
