### ISSUE TITLE
`post_release()`: Delete branch after merge

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#43]
When run locally.

On CI: open PR via `pr_push()`? Maybe even earlier, in `pre_release()`?

**Comment by krlmlr** [comment]
Not sure this is fledge's responsibility.

**Comment by pat-s** [comment]
FYI: This is done automatically by `gh` (by default) when merging a PR.

**Comment by krlmlr** [comment]
Still not sure this is fledge's responsibility.
