### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#5]
~~and submit to CRAN.~~

**Comment by krlmlr** [comment]
We can focus on snapshot tests for now. We can set a few environment variables to keep output stable (including Git SHAs), the vignette already has code that does it.

**Comment by krlmlr** [comment]
I have `galley.R`, `aaa-galley.R` and `test-vignette-*.R` in tibble, these can be copied so that we get snapshot tests for vignettes. Let's add formal tests later.

**Comment by maelle** [comment]
Actually is this a duplicate of #103

**Comment by krlmlr** [comment]
This issue is about adding "any kind of test", #103 is about formal tests for internal functions. Testing the vignettes (including their output) is a start, maybe we don't need to strictly separate both kinds of test.

**Comment by maelle** [comment]
What do you mean by formal tests?

**Comment by krlmlr** [comment]
A regular explicit `test_that("some behavior", { ... })`, as opposed to a snapshot test.
