### ISSUE TITLE
FIXME in create_pull_request()

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#504]
@krlmlr could you please clarify

https://github.com/cynkra/fledge/blob/462cd381ddb1378b41dc87060f935725ce9a70d5/R/auto.R#L442

**Comment by krlmlr** [comment]
I think this was about checking if a PR with that branch is already open? Might be obsolete now, no idea.

**Comment by krlmlr** [comment]
We'll fix it when needed.
