### ISSUE TITLE
Mention required PAT scopes in NEWS/README?

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#571]
While using fledge today, I fell across the new PAT scopes which are required.

```r
Error in `check_gh_pat()`:
! ✖ Missing scopes for GitHub GraphQL API (used for finding issues linked to PR): read:packages, read:org, read:public_key, read:repo_hook, user, read:discussion, read:enterprise, read:gpg_key
ℹ See https://docs.github.com/en/graphql/guides/forming-calls-with-graphql
```

While updating my PAT, I had the feeling that the required scopes are quite a few to grant. Might potentially scare away some users?

**Comment by maelle** [comment]
Right, this should be revisited with https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/

I fear that finding the correct permissions for the GraphQL API will take some trial and error, but it's definitely worth the effort.

**Comment by maelle** [comment]
Or we could remove the check entirely since I now see the docs say

> The API notifies you if a resource requires a specific scope.

https://docs.github.com/en/graphql/guides/forming-calls-with-graphql

**Comment by maelle** [comment]
Result from a first test

> GitHub API error (401): Personal access tokens with fine grained access
  do not support the GraphQL API

I hope it will be the case in the future, I'll now try and find the minimal scopes for coarse-grained tokens. :grin:

**Comment by maelle** [comment]
ouch, no scope needed! will make a PR shortly, sorry for the initial mistake.

**Comment by maelle** [comment]
see #572

**Comment by pat-s** [comment]
I needed quite a lot of scopes in my PAT. 

Do you mean fledge actually does not make use of the scopes and hence they could be avoided? 🙂 

(just quickly skimmed over your comments on the go)

**Comment by maelle** [comment]
yes! fledge uses the "repo" scope for the release automation, and for the V4 API I had mistakenly thought it needed all these other scopes whereas it does NOT need them so my PR removes that constraint. Sorry and thanks for reporting!

**Comment by pat-s** [comment]
Ah great to hear :) I already wondered a bit but didn't think too much about it.
