### ISSUE TITLE
Watch out for "generated by" header

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#596]
and turn into a no-op if missing.

Perhaps only in non-interactive mode?

I want to deploy the fledge workflow "everywhere", but enable it only for repos that already use fledge.

**Comment by maelle** [comment]
It's a pity `read_fledgeling()` adds a preamble if it's not present.

**Comment by krlmlr** [comment]
`read_fledgeling()` is new and private, we can still change it?
