### ISSUE TITLE
fledge can't parse all Markdown header formats

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#599]
At the moment when creating fledgeling objects we rely on a regular expression to find version headers. But if a header has the format

```
fledge 1.0.0
===
```

we do not recognize it because the header is created on the second line.

I noticed this in the roundtrip.

I think we should
- indicate the current limitation
- or parse the NEWS.md with Pandoc directly, not just later.

@krlmlr opinion?

**Comment by krlmlr** [comment]
No particular opinion. The roundtrip should look natural, perhaps as similarly as possible to existing NEWS files. I don't mind small changes like those.

**Comment by krlmlr** [comment]
The other option is to avoid touching old NEWS items by default, and make normalization an explicit process.

**Comment by maelle** [comment]
even if we don't touch them by default it'd be nice to be able to parse them if needed :-) I'll think about the necessary refactoring.
