### ISSUE TITLE
A new release and updated NEWS.md?

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#603]
The current changelog is somewhat hard to read/follow. The last official release dates back to 2021. 

Would it be a good time for a new release with a cleaned up changelog?

**Comment by maelle** [comment]
wow time flies (not a pun :hatching_chick: ). We're working on 1.0.1, in particular #588 is taking a lot of time. Sorry and thank you for your patience.

**Comment by krlmlr** [comment]
On it.
