### ISSUE TITLE
Accidental merges of the main branch into the release branch

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#614]
Actions:

- `pre_release()`
- `git merge origin/main`

This leads to an unfortunate situation where the version is at .9000 again and `NEWS.md` contains bad entries. This is difficult to recover from.

Should we avoid preparing the .9000 version before `post_release()` has been called? Do we even need the release branch?

**Comment by maelle** [comment]
is this still valid?

**Comment by krlmlr** [comment]
Will be closed with the split PR.
