### ISSUE TITLE
`pre_release()`: trigger CI run with release version before bumping to dev again

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#64]
Currently we 

- bump to the release version
- bump to the dev version again

without triggering a CI run on the main branch with the release version.
This is problematic if someones builds a release/dev pkgdown site where the release version is only triggered when a three-component version is present during a run on the main branch (we currently do in mlr-org).

Adding another `git push` before bumping to the dev version again won't be a problem, will it?

**Comment by krlmlr** [comment]
I don't think the push will really help. We need a push after the package has been accepted, but before actually merging into main. I think pkgdown builds should respond to tag events too?
