### ISSUE TITLE
`rstudioapi::sendToConsole()` errors in vscode

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#68]
```r
Error in rstudioapi::sendToConsole(code, execute = FALSE) : 
  This {rstudioapi} function is not currently implemented for VSCode.
```

Needs to be conditioned.

**Comment by krlmlr** [comment]
Or fixed up/downstream ;-)

**Comment by pat-s** [comment]
Don't think that this will happen. Miles added initial support for {rstudioapi} but this specific one might be tricky. 

Isn't there an R base equivalent?

**Comment by krlmlr** [comment]
Should work now.
