### ISSUE TITLE
Long-term collaboration/planning

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#72]
I've branched off quite a bit in some PRs meanwhile and it becomes a bit exhausting to import all main branch changes 1to1 while keeping the discussion going - how do we proceed here?

Do we want to maintain different, opionated approaches in one repo and stating this in the README? Should I fork and import upstream changes selectively?
I want to avoid heavy arguiung on opinionated details and also push development forward because I consider this as a great project.

Currently I see (partly) different views on the following details:

- Levels of automation (cran mail processing and more)
- RC or not
- git2r vs gert

**Comment by pat-s** [comment]
Are there any plans to move forward with these ideas/PRs? Otherwise I would branch off soon (this week or so).

**Comment by krlmlr** [comment]
Yeah, let's discuss.

**Comment by krlmlr** [comment]
- gert PR merged
- implemented extension points so that new code can reside entirely in new files; if necessary, will consider formal extension mechanism at some point
- RC tags undecided, would review a minimal PR
