### ISSUE TITLE
Consider using a cynkra.com subdomain for pkgdown

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#79]

**Comment by krlmlr** [comment]
Sure, let's experiment here and set up a plan how these are managed.

**Comment by pat-s** [comment]
I am not sure what you mean by this.

**Comment by krlmlr** [comment]
https://github.com/cynkra/cynkratemplate/issues/6

**Comment by maelle** [comment]
Maybe relevant for inspiration https://ropensci.org/blog/2021/09/03/runiverse-docs/

**Comment by maelle** [comment]
Actually I'll link this to #79
