### ISSUE TITLE
Keep fledge NEWS.md disclaimer always on top

### ISSUE THREAD

**Issue by pat-s** [cynkra/fledge#83]
After a release and bumping the version again while scraping one news-worthy commit, `NEWS.md` now look like

```md
# mlr3spatiotempcv 0.2.1.9001

- Skip a test on Solaris and macOS 3.6


<!-- NEWS.md is maintained by https://cynkra.github.io/fledge, do not edit -->

# mlr3spatiotempcv 0.2.1.9000

- Same as previous version.

```

**Comment by krlmlr** [comment]
Weird, I need to double-check what happens.

**Comment by pat-s** [comment]
When calling `pre_release()` again from this state, another disclaimer entry gets added to the top.
Is this expected or maybe even a separate issue?

The other one, which got shifted down, is still there and then needs manual cleanup.

Looks like `bump_version()` did not respect the header when updating `NEWS.md`.

**Comment by krlmlr** [comment]
Is this still a problem?

**Comment by pat-s** [comment]
Haven't seen this lately anymore.
