### ISSUE TITLE
pre_release(): combine all NEWS items from previous development releases

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#97]
automatically, keep a `# 1.6.0.9999` header to ensure that it is still edited.

**Comment by maelle** [comment]
Seems related to #147, and useful

**Comment by krlmlr** [comment]
If conventional commits (#145) are used, we would also distribute the NEWS items under second-level headings.

**Comment by maelle** [comment]
and order them

**Comment by maelle** [comment]
Also

- remove "Same as previous version."
- If there's any other item, remove "Internal changes only."?

**Comment by maelle** [comment]
For this and conventional commit parsing, should fledge take a dependency on https://github.com/ropensci/tinkr/? :innocent: With tinkr one can do Markdown to XML, XML wrangling (with xml2), XML back to Markdown.

**Comment by maelle** [comment]
(tinkr should get on CRAN soon-ish https://github.com/ropensci/tinkr/issues/43#issuecomment-1073995952)

**Comment by maelle** [comment]
another thing that's needed is parsing of the version headers.
- it should work with the same syntaxes as what pkgdown supports (so h1 or h2, with/without the package name).
- it should be able to strip the date, hopefully the data is always at the end between parentheses.
- it should be able to assess what version numbers are dev ones (4 components).

**Comment by krlmlr** [comment]
Should this discussion and decision be part of #331, turning that issue into a blocker here?

**Comment by krlmlr** [comment]
This and many many other issues will be much easier with #331.

**Comment by zkamvar** [comment]
> (tinkr should get on CRAN soon-ish [ropensci/tinkr#43 (comment)](https://github.com/ropensci/tinkr/issues/43#issuecomment-1073995952))

soon-ish is now :)

**Comment by maelle** [comment]
combining would "easily" work with #588, I tried the code below on fledge itself.

```r
fledgling <- read_fledgling()
regroup_news(
    unlist(
      fledgling$news[1:(nrow(fledgling$news) - 1),]$news,
      recursive = FALSE
  )
)
```

**Comment by maelle** [comment]
Special care will be needed for "Internal changes only" (to be removed if there are other items!)

**Comment by maelle** [comment]
I think this combining should happen in `bump_version()` or something else lower level than `pre_release()` so that people who use a workflow like #147 can benefit. :thinking:

**Comment by maelle** [comment]
should this go in milestone 1.0.1, as a low-hanging fruit ?

**Comment by krlmlr** [comment]
Is it low-hanging now?

I haven't reviewed the milestones in a while.

**Comment by maelle** [comment]
it will be once #588 is merged, at least I think so.
